#pragma once

#include <windows.h>
#include <stdio.h>
#include <assert.h>

#define WINPFILTER_DEVICE_NAME L"\\\\.\\winpfilter_r3cmd_com_device"


#define WINPFILTER_CTL_CODE_BY_INDEX(index) CTL_CODE(FILE_DEVICE_UNKNOWN,0x800+index, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_VERSION			CTL_CODE(FILE_DEVICE_UNKNOWN,0x800, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_FORWARDING_MODE CTL_CODE(FILE_DEVICE_UNKNOWN,0x801, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_RX_BAD_IP_CSUM	CTL_CODE(FILE_DEVICE_UNKNOWN,0x802, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_RX_BAD_TCP_CSUM CTL_CODE(FILE_DEVICE_UNKNOWN,0x803, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_RX_BAD_UDP_CSUM CTL_CODE(FILE_DEVICE_UNKNOWN,0x804, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_TX_NIC_IP_CSUM  CTL_CODE(FILE_DEVICE_UNKNOWN,0x805, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_TX_NIC_TCP_CSUM CTL_CODE(FILE_DEVICE_UNKNOWN,0x806, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_TX_NIC_UDP_CSUM CTL_CODE(FILE_DEVICE_UNKNOWN,0x807, METHOD_BUFFERED,FILE_ALL_ACCESS)
#define WINPFILTER_CTL_CODE_HOOK_INFO		CTL_CODE(FILE_DEVICE_UNKNOWN,0x808, METHOD_BUFFERED,FILE_ALL_ACCESS)

#define WPFILTER_VERSION 20241015

#pragma pack (1)
typedef struct _HOOK_INFO {
	ULONG	Priority;
	PVOID	HookFunction;
}HOOK_INFO, * PHOOK_INFO;
#pragma pack ()

VOID SetConsoleWarning();

VOID SetConsoleError();

VOID SetConsoleDefault();